### ISSUE TITLE
not able to set secret key 

### ISSUE THREAD

**Issue by prerak007-maker** [nagarajpandith/cas#17]
please if you don't mind plz connect on teamviewer and fix this.
![Screenshot (84)](https://github.com/nagarajpandith/cas/assets/55207204/ad71c1a5-5f57-4302-9de2-20bbd98480df)

**Comment by nagarajpandith** [comment]
follow the local setup instructions carefully: [read here](https://github.com/nagarajpandith/cas#local-setup)
the guide clearly asks you to create an .env file in the root folder and fill the variables.
